---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/voxpupuli/puppet-augeasproviders_core
    mount_providers: https://github.com/puppetlabs-toy-chest/puppetlabs-mount_providers.git
